name: project deploy

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: run test
        id: checkTest
        run: yarn test
  cd:
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSHKEY }}
          source: "build/"
          target: "/var/www/testnode/web"
